name: "internship-system"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 8088:80
    env_file:
      - .env
    depends_on:
      - db

  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    hostname: 'localhost'
    healthcheck:
      test: curl http://localhost:9876/-/health || exit 1
      interval: 1m
      start_period: 10m
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://localhost:9876"
        gitlab_rails['initial_root_password'] = '${GITLAB_INIT_PASSWORD}'
    ports:
      - '9876:9876'
      - '444:443'
      - '23:22'
    volumes:
      - '${HOST_GITLAB_CONFIG_DIR}:${GITLAB_CONFIG_DIR}'
      - '${HOST_GITLAB_LOGS_DIR}:${GITLAB_LOGS_DIR}'
      - '${HOST_GITLAB_DATA_DIR}:${GITLAB_DATA_DIR}'
    shm_size: '256m'

  main-service:
    image: main-service
    container_name: main-service
    build:
      context: .
      dockerfile: main-service/Dockerfile
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_started
      gitlab-service:
        condition: service_healthy
    env_file:
      - .env

  gitlab-service:
    image: gitlab-service
    container_name: gitlab-service
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 60s
    build:
      context: .
      dockerfile: gitlab-service/Dockerfile
    restart: always
    ports:
      - 9090:9090
    depends_on:
      db:
        condition: service_started
      gitlab-ce:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - GITLAB_PASSWORD=${GITLAB_INIT_PASSWORD}